// persistence — SSH-key auth, account registry, and player save round-tripping.

export {
	type AccountRegistry,
	AUTH_CONTEXT,
	type AuthResult,
	type ClaimResult,
	canonicalPublicKey,
	challengePayload,
	claimHandle,
	createAccountRegistry,
	encodePublicKeyLine,
	encodeSignatureBlob,
	HANDLE_CHAR_RE,
	HANDLE_MAX_LEN,
	HANDLE_MIN_LEN,
	HANDLE_RE,
	handleForKey,
	NONCE_LEN,
	parsePublicKeyBlob,
	parsePublicKeyLine,
	resolveAuth,
	SSH_ED25519,
	SshBlobReader,
	SshBlobWriter,
	type SshPublicKey,
	validHandle,
	verifyChallenge,
} from './auth';
export {
	emptySave,
	migrateSaveCosmetics,
	type PlayerSave,
	type PlayerStore,
	type RestoredAvatar,
	registryFromSaves,
	restoredFromSave,
	saveFromAvatar,
} from './persistence';
