// Minimal authored content for injected-entries tests: one catalog, one Town,
// one Field with a spawn and a portal, shared by the store/zone suites.
export const CATALOGS_JSON =
	'{"monsters":[{"id":"slime","behavior":"chaser","name":"Slime"}],"npcs":[]}';

export const FIELD_TEXT = `{"type":"field","spawns":{"c":"slime"},"portals":{"P":{"target":"t","arrival":[2,7]}}}
---
..........
..........
..........
....c.....
..........
..P.......
..........
..........
##########`;

export const TOWN_TEXT = `{"type":"town","portals":{"P":{"target":"f","arrival":[2,7]}}}
---
..........
..........
..........
..........
..........
..P.......
..........
..........
##########`;
